name: Generate Readme

on:
  push:
    branches:
      - "main"

jobs:
  generate_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace Templates
        run: |
          # Explanation of yq command
          # ---
          # 1. Flag '-M' means no colored output.
          # 2. '.templates[]' acts as a for loop for the keys inside it.
          # 3. 'key' grabs the key for the item in the for loop running in step 2.
          # 4. '.description // ""' means of description is null return an empty string.

          export TEMPLATES=$(yq -M eval '.templates[] | "| " + key + " | " + .description // "" + " |"' sandbox-config.yaml)

          envsubst < _README.md > README.md

      - name: Commit & Push
        run: |
          git config user.name "Github Actions Bot"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "docs: generate README.md"
          git push origin main
