name: Generate Readme

on:
  push:
    branches:
      - "main"

jobs:
  generate_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace Templates
        run: |
          echo $PWD
          ls
          export TEMPLATES=$(yq -M eval '.templates[] | "| " + key + " | " + .description // "" + " |"' sandbox-config.yaml)
          envsubst < _README.md > README.md

      - name: Commit & Push
        run: |
          git config --global user.name "Github Actions Bot"
          git config --global user.email "gurleensethi@users.noreply.github.com"
          git add README.md
          git commit -m "docs: generate README.md"
          git push origin main
