name: Generate Readme

on:
  push:
    branches:
      - "main"

jobs:
  generate_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Replace Templates
        run: |
          echo $PWD
          export TEMPLATES=$(yq -M eval '.templates[] | "- " + key + " - " + .description // ""' sandbox-config.yaml)
          echo $TEMPLATES
          envsubst < _README.md
